---
- hosts: all
  become: true
  tasks:          

  - name: install pip
    apt:
      name: python-pip

  - name: Install ansible 2.2
    pip:
      name: ansible
      version: 2.2
      executable: pip

  - name: Install required packages apt
    apt: pkg={{ item }} state=latest
    with_items:
      - python-scipy
      - python-numpy
      - python-pandas

  - name: install pip3
    apt: name=python3-pip state=present 

  - name: Install required packages pip
    pip: name={{ item }}
    with_items:
      - scikit-learn
